trigger:
- 'main'

variables:
  buildConfiguration: 'Release'
  leaderboardRepository: 'leaderboard'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'
  acrServiceConnection: 'Container Registry Connections'
  acrLoginServer: 'tailspinspacegame17818.azurecr.io'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
    - job: 'Build'
      displayName: 'Build Docker images'
      pool:
        vmImage: 'ubuntu-22.04'

      steps:
        - task: Docker@2
          displayName: 'Build & Push Web Image'
          inputs:
            command: buildAndPush
            buildContext: $(Build.Repository.LocalPath)
            repository: $(webRepository)
            dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
            containerRegistry: $(acrServiceConnection)
            tags: |
              $(tag)

        - task: Docker@2
          displayName: 'Build & Push Leaderboard Image'
          inputs:
            command: buildAndPush
            buildContext: $(Build.Repository.LocalPath)
            repository: $(leaderboardRepository)
            dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
            containerRegistry: $(acrServiceConnection)
            tags: |
              $(tag)

        - publish: '$(Build.SourcesDirectory)/manifests'
          artifact: manifests

- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
    - deployment: Deploy
      displayName: Deploy to AKS
      pool:
        vmImage: 'ubuntu-22.04'
      environment: 'kubernetesdev'
      variables:
        - group: Release
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: manifests

              - task: KubernetesManifest@1
                displayName: 'Deploy to AKS'
                inputs:
                  action: deploy
                  connectionType: azureResourceManager
                  azureSubscriptionConnection: 'Kubernetes Cluster Connection'
                  azureResourceGroup: 'tailspin-space-game-rg'
                  kubernetesCluster: 'tailspinspacegame-17818'
                  namespace: 'default'
                  manifests: |
                    $(Pipeline.Workspace)/manifests/deployment.yml
                    $(Pipeline.Workspace)/manifests/service.yml
                  imagePullSecrets: |
                    $(imagePullSecret)
                  containers: |
                    $(acrLoginServer)/$(webRepository):$(tag)
                    $(acrLoginServer)/$(leaderboardRepository):$(tag)
